Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2020-08, with the labels that each got.

#111 open membership acctest
  azuredevops/internal/acceptancetests/resource_group_membership_test.go
Labels: size/XS

#110 Support build report status configuration
  azuredevops/internal/service/build/resource_build_definition.go
  azuredevops/internal/service/build/resource_build_definition_test.go
  website/docs/r/build_definition.html.markdown
Labels: documentation, enhancement, size/XS

#119 Add ACR service connection resource
  azuredevops/internal/acceptancetests/resource_serviceendpoint_azurecr_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr_test.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/docs/r/serviceendpoint_azurecr.html.markdown
Labels: documentation, size/XL

#131 variable group example import syntax correction
  website/docs/r/variable_group.html.markdown
Labels: documentation, size/XS

#127 Changelog update
  CHANGELOG.md
Labels: size/XS

#126 Document update
  website/docs/r/build_definition.html.markdown
  website/docs/r/serviceendpoint_dockerhub.html.markdown
  website/docs/r/serviceendpoint_dockerregistry.html.markdown
Labels: documentation, size/S

#85 New resources for managing permissions on Areas and Iterations
  azuredevops/internal/acceptancetests/data_area_test.go
  azuredevops/internal/acceptancetests/data_iteration_test.go
  azuredevops/internal/acceptancetests/resource_area_permissions_test.go
  azuredevops/internal/acceptancetests/resource_iteration_permissions_test.go
  azuredevops/internal/acceptancetests/resource_workitemquery_permissions_test.go
  azuredevops/internal/service/permissions/resource_area_permissions.go
  azuredevops/internal/service/permissions/resource_iteration_permissions.go
  azuredevops/internal/service/permissions/utils/classification.go
  azuredevops/internal/service/permissions/utils/classification_test.go
  azuredevops/internal/service/workitemtracking/data_area.go
  azuredevops/internal/service/workitemtracking/data_iteration.go
  azuredevops/internal/service/workitemtracking/utils/classification.go
  azuredevops/internal/service/workitemtracking/utils/classification_test.go
  azuredevops/internal/utils/datahelper/data_helper.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/azuredevops.erb
  website/docs/d/data_area.html.markdown
  website/docs/d/data_iteration.html.markdown
  website/docs/r/area_permissions.html.markdown
  website/docs/r/iteration_permissions.html.markdown
Labels: dependencies, documentation, new-data-source, new-feature, new-resource, size/XXL

#134 Github service connection update
  azuredevops/internal/acceptancetests/resource_serviceendpoint_github_test.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_github.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_github_test.go
  website/docs/r/variable_group.html.markdown
Labels: documentation, size/XS

#118 Support import git repository
  azuredevops/internal/acceptancetests/resource_git_repository_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/git/resource_git_repository.go
  website/docs/r/azure_git_repository.html.markdown
Labels: documentation, enhancement, size/L

#147 Nil checks to fix #146
  azuredevops/internal/service/git/resource_git_repository.go
Labels: size/XS

#144 Add work item linking and comment resolution branch policies
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/service/policy/common.go
  azuredevops/internal/service/policy/resource_branchpolicy_comment_resolution.go
  azuredevops/internal/service/policy/resource_branchpolicy_comment_resolution_test.go
  azuredevops/internal/service/policy/resource_branchpolicy_work_item_linking.go
  azuredevops/internal/service/policy/resource_branchpolicy_work_item_linking_test.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/azuredevops.erb
  website/docs/r/branch_policy_comment_resolution.html.markdown
  website/docs/r/branch_policy_work_item_linking.html.markdown
Labels: documentation, new-feature, new-resource, size/XL

#148 Change log update
  CHANGELOG.md
Labels: size/XS

#150 Location of golanci-lint is not always in gopath
  GNUmakefile
Labels: size/XS

#151 Do not set a default agent pool name
  azuredevops/internal/service/build/resource_build_definition.go
  website/docs/r/build_definition.html.markdown
Labels: documentation, size/XS

#149 Refactoring of permission resources and their corresponding helper methods
  azuredevops/internal/service/permissions/resource_area_permissions.go
  azuredevops/internal/service/permissions/resource_git_permissions.go
  azuredevops/internal/service/permissions/resource_git_permissions_test.go
  azuredevops/internal/service/permissions/resource_iteration_permissions.go
  azuredevops/internal/service/permissions/resource_project_permissions.go
  azuredevops/internal/service/permissions/resource_project_permissions_test.go
  azuredevops/internal/service/permissions/resource_workitemquery_permissions.go
  azuredevops/internal/service/permissions/resource_workitemquery_permissions_test.go
  azuredevops/internal/service/permissions/utils/namespaces.go
  azuredevops/internal/service/permissions/utils/namespaces_test.go
  azuredevops/internal/service/permissions/utils/securityHelper.go
Labels: size/XL

#156 Variable group allow access inconsistent
  azuredevops/internal/acceptancetests/resource_variable_group_test.go
  azuredevops/internal/service/taskagent/resource_variable_group.go
  azuredevops/internal/service/taskagent/resource_variable_group_test.go
Labels: size/S

#157 Added support for Terraform v0.13 provider installation
  scripts/commons.ps1
  scripts/commons.sh
  scripts/local-install.ps1
  scripts/local-install.sh
Labels: size/M
