Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2020-06, with the labels that each got.

#1 Update Readme
  README.md
Labels: documentation, size/XS

#9 This change adds a missing reference to project_features documentation
  website/azuredevops.erb
Labels: documentation, size/XS

#13 Add Resource Authorization missing navigation
  website/docs/d/data_agent_pool.html.markdown
  website/docs/d/data_group.html.markdown
  website/docs/d/data_project.html.markdown
  website/docs/d/data_users.html.markdown
  website/docs/guides/authenticating_using_the_personal_access_token.html.md
  website/docs/index.html.markdown
  website/docs/r/agent_pool.html.markdown
  website/docs/r/agent_queue.html.markdown
  website/docs/r/azure_git_repository.html.markdown
  website/docs/r/branch_policy_build_validation.html.markdown
  website/docs/r/branch_policy_min_reviewers.html.markdown
  website/docs/r/build_definition.html.markdown
  website/docs/r/group.html.markdown
  website/docs/r/group_membership.html.markdown
  website/docs/r/project.html.markdown
  website/docs/r/project_features.html.markdown
  website/docs/r/resource_authorization.html.markdown
  website/docs/r/serviceendpoint_azurerm.html.markdown
  website/docs/r/serviceendpoint_bitbucket.html.markdown
  website/docs/r/serviceendpoint_dockerhub.html.markdown
  website/docs/r/serviceendpoint_dockerregistry.html.markdown
  website/docs/r/serviceendpoint_github.html.markdown
  website/docs/r/serviceendpoint_kubernetes.html.markdown
  website/docs/r/user_entitlement.html.markdown
  website/docs/r/variable_group.html.markdown
Labels: documentation, size/XL

#16 Make link text correspond to resource type name
  website/azuredevops.erb
Labels: documentation, size/XS

#14 Update extension names
  .devcontainer/devcontainer.json
Labels: size/XS
