Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2020-07, with the labels that each got.

#24 GitHub CI script update
  .github/workflows/check-pr.yml
Labels: size/M

#55 Update azure_git_repository.html.markdown
  website/docs/r/azure_git_repository.html.markdown
Labels: documentation, size/XS

#57 Fix 400 bad request not found
  azuredevops/internal/service/build/resource_resource_authorization.go
  azuredevops/internal/utils/HttpResponse.go
  azuredevops/internal/utils/HttpResponse_test.go
Labels: size/M

#60 Fix Service connection description nil panic and document update
  azuredevops/internal/service/serviceendpoint/commons.go
  website/docs/r/serviceendpoint_azurerm.html.markdown
Labels: documentation, enhancement, size/XS

#66 Correcting docs for permission resources
  website/azuredevops.erb
  website/docs/r/git_permissions.html.markdown
  website/docs/r/project_permissions.html.markdown
Labels: documentation, size/S

#67 bitbucket acceptance test update
  azuredevops/internal/acceptancetests/resource_serviceendpoint_bitbucket_test.go
Labels: size/XS

#58 Add AWS Service Endpoint resource
  azuredevops/internal/acceptancetests/resource_serviceendpoint_aws_test.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_aws.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_aws_test.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/azuredevops.erb
  website/docs/r/serviceendpoint_aws.html.markdown
Labels: documentation, new-feature, new-resource, size/XL

#70 Adding changelog link to docs
  website/docs/index.html.markdown
Labels: documentation, size/XS

#75 Use correct repo url
  docs/contributing.md
  examples/github-based-cicd-simple/README.md
  examples/github-based-cicd-simple/main.tf
  website/docs/index.html.markdown
Labels: documentation, size/XS

#71 feat: Auto reviewer branch policy
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/service/policy/common.go
  azuredevops/internal/service/policy/resource_branchpolicy_auto_reviewers.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  go.sum
  website/docs/r/branch_policy_auto_reviewers.html.markdown
Labels: dependencies, documentation, size/L

#78 make test and make testacc file filter update
  GNUmakefile
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
Labels: size/XS

#83 kubernetes service connection document update
  website/docs/r/serviceendpoint_kubernetes.html.markdown
Labels: documentation, size/XS

#17 Add build definition auth
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  GNUmakefile
  README.md
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/acceptancetests/resource_build_definition_test.go
  azuredevops/internal/acceptancetests/resource_git_repository_test.go
  azuredevops/internal/acceptancetests/resource_project_test.go
  azuredevops/internal/acceptancetests/resource_resource_authorization_test.go
  azuredevops/internal/acceptancetests/resource_serviceendpoint_azurerm_test.go
  azuredevops/internal/acceptancetests/resource_variable_group_test.go
  azuredevops/internal/acceptancetests/testutils/commons.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/build/resource_build_definition.go
  azuredevops/internal/service/build/resource_resource_authorization.go
  azuredevops/internal/service/build/resource_resource_authorization_test.go
  azuredevops/internal/service/core/data_projects.go
  azuredevops/internal/service/core/resource_project.go
  azuredevops/internal/service/git/data_git_repositories.go
  azuredevops/internal/service/git/data_git_repository.go
  azuredevops/internal/service/git/resource_git_repository.go
  azuredevops/internal/service/graph/data_users.go
  azuredevops/internal/service/memberentitlementmanagement/resource_user_entitlement.go
  azuredevops/internal/service/permissions/resource_git_permissions.go
  azuredevops/internal/service/permissions/resource_project_permissions.go
  azuredevops/internal/service/permissions/utils/baseSchema.go
  azuredevops/internal/service/permissions/utils/baseSchema_test.go
  azuredevops/internal/service/serviceendpoint/commons.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_github.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go
  azuredevops/internal/service/taskagent/resource_agentpool.go
  azuredevops/internal/service/taskagent/resource_variable_group.go
  azuredevops/internal/utils/validate/strings.go
  azuredevops/internal/utils/validate/strings_test.go
  azuredevops/internal/utils/validate/uuid.go
  azuredevops/internal/utils/validate/uuid_test.go
  docs/debugging.md
  docs/testing.md
  website/docs/r/agent_queue.html.markdown
  website/docs/r/build_definition.html.markdown
  website/docs/r/resource_authorization.html.markdown
Labels: documentation, new-feature, size/XXL

#84 Fix VSCode settings
  .vscode/launch.json
  .vscode/settings.json
Labels: size/XS

#73 Add "Path filter" support for repository build policy
  azuredevops/internal/acceptancetests/data_project_test.go
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/policy/common.go
  azuredevops/internal/service/policy/common_test.go
  azuredevops/internal/service/policy/resource_branchpolicy_build_validation.go
  azuredevops/internal/service/policy/resource_branchpolicy_build_validation_test.go
  azuredevops/internal/service/serviceendpoint/commons.go
  website/docs/r/branch_policy_build_validation.html.markdown
Labels: documentation, enhancement, size/XL

#74 GitHub service connection API breaking change
  azuredevops/internal/acceptancetests/resource_serviceendpoint_github_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_github.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_github_test.go
  website/docs/r/agent_queue.html.markdown
Labels: documentation, size/L

#88 changelog update
  CHANGELOG.md
Labels: size/XS

#87 Update VSCode debugging settings
  .vscode/settings.json
Labels: size/XS

#91 Updated chapter about debugging tests from VS Code in docs/debugging.md
  docs/debugging.md
Labels: size/XS

#92 Make `initialization` a required field in `azuredevops_git_repository`
  azuredevops/internal/acceptancetests/resource_git_repository_test.go
  azuredevops/internal/service/git/resource_git_repository.go
  azuredevops/internal/service/git/resource_git_repository_test.go
Labels: enhancement, size/S

#93 Fix acceptance tests
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/acceptancetests/resource_serviceendpoint_bitbucket_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
Labels: size/XS

#95 Replaced static email in branchpolicy tests
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
Labels: size/XS

#89 Use the default_branch as the name of an initialized branch instead of defaulting to master
  azuredevops/internal/service/git/resource_git_repository.go
  azuredevops/internal/service/git/resource_git_repository_test.go
  website/docs/r/azure_git_repository.html.markdown
Labels: documentation, enhancement, size/M

#96 Refactor acceptance tests
  azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
  azuredevops/internal/acceptancetests/resource_serviceendpoint_aws_test.go
Labels: size/XS

#102 Changelog update
  CHANGELOG.md
  website/docs/r/azure_git_repository.html.markdown
Labels: documentation, size/XS

#97 Add Support for GitHub enterprise as a build definition repository type
  azuredevops/internal/model/repo.go
  azuredevops/internal/service/build/resource_build_definition.go
  azuredevops/internal/service/build/resource_build_definition_test.go
  website/docs/r/build_definition.html.markdown
Labels: documentation, enhancement, size/L

#103 Hardcode dummy values
  azuredevops/internal/acceptancetests/resource_serviceendpoint_aws_test.go
  azuredevops/internal/acceptancetests/resource_serviceendpoint_bitbucket_test.go
  azuredevops/internal/acceptancetests/resource_serviceendpoint_dockerregistry_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
Labels: size/M

#105 Fix create build definition with Github failed
  azuredevops/internal/service/build/resource_build_definition.go
  azuredevops/internal/service/build/resource_build_definition_test.go
Labels: size/XS

#108 Remove misleading import references
  website/docs/r/azure_git_repository.html.markdown
Labels: documentation, size/XS

#109 changelog update
  CHANGELOG.md
Labels: size/XS

#79 New resource azuredevops_workitemquery_permissions
  azdosdkmocks/workitemtracking_sdk_mock.go
  azuredevops/internal/acceptancetests/resource_workitemquery_permissions_test.go
  azuredevops/internal/client/client.go
  azuredevops/internal/service/permissions/resource_workitemquery_permissions.go
  azuredevops/internal/service/permissions/resource_workitemquery_permissions_test.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  vendor/github.com/microsoft/azure-devops-go-api/azuredevops/workitemtracking/client.go
  vendor/github.com/microsoft/azure-devops-go-api/azuredevops/workitemtracking/models.go
  vendor/modules.txt
  website/azuredevops.erb
  website/docs/r/workitemquery_permissions.html.markdown
Labels: dependencies, documentation, new-feature, size/XXL
