Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2023-11, with the labels that each got.

#917 Add ability to fetch environment by name
  azuredevops/internal/acceptancetests/data_environment_test.go
  azuredevops/internal/service/taskagent/data_environment.go
  website/docs/d/environment.html.markdown
Labels: enhancement

#916 feat: add attribute queue_status to resource azuredevops_build_definition
  azuredevops/internal/service/build/data_build_definition.go
  azuredevops/internal/service/build/resource_build_definition.go
  website/docs/d/build_definition.html.markdown
  website/docs/r/build_definition.html.markdown
Labels: enhancement

#921 [Bug Fix] - `azuredevops_serviceendpoint_azurerm` - Fix azrerrm deleted but still returns to exist
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go
Labels: bug

#865 adding validation feature to azuredevops_serviceendpoint_azurerm reso…
  GNUmakefile
  azuredevops/internal/acceptancetests/resource_serviceendpoint_azurerm_test.go
  azuredevops/internal/acceptancetests/testutils/hcl.go
  azuredevops/internal/service/serviceendpoint/commons.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm_test.go
  azuredevops/internal/service/taskagent/resource_variable_group.go
  website/docs/r/serviceendpoint_azurerm.html.markdown
Labels: enhancement, service connection

#929 `azuredevops_pipeline_authorization` - Add retry for pipeline authorization
  azuredevops/internal/service/build/resource_pipeline_authorization.go
Labels: enhancement

#906 Make `agent_pool_id` optional in resource `azuredevops_agent_queue`
  azuredevops/internal/service/taskagent/resource_agent_queue.go
  website/docs/r/agent_queue.html.markdown
Labels: enhancement
