Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2024-03, with the labels that each got.

#981 `azuredevops_team` - Fixing the team admin flags
  azuredevops/internal/service/core/resource_team.go
  azuredevops/internal/service/core/resource_team_test.go
Labels: bug

#973 `azuredevops_pipeline_authorization` - Allow pipeline authorization across projects
  azuredevops/internal/acceptancetests/resource_pipeline_authorization_test.go
  azuredevops/internal/service/build/resource_pipeline_authorization.go
  website/docs/r/pipeline_authorization.html.markdown
Labels: enhancement

#956 Add Data_sources for on-premise User and Group(s)
  azuredevops/internal/acceptancetests/data_identity_group_test.go
  azuredevops/internal/acceptancetests/data_identity_groups_test.go
  azuredevops/internal/acceptancetests/data_identity_users_test.go
  azuredevops/internal/service/identity/data_identity_group.go
  azuredevops/internal/service/identity/data_identity_group_test.go
  azuredevops/internal/service/identity/data_identity_groups.go
  azuredevops/internal/service/identity/data_identity_groups_test.go
  azuredevops/internal/service/identity/data_identity_user.go
  azuredevops/internal/service/identity/data_identity_user_test.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/docs/d/identity_group.html.markdown
  website/docs/d/identity_groups.html.markdown
  website/docs/d/identity_users.html.markdown
Labels: new-data-source
