Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2024-10, with the labels that each got.

#1184 `azuredevops_agent_queue` - Enhance `name` validation
  azuredevops/internal/service/taskagent/data_agent_queue.go
  azuredevops/internal/service/taskagent/resource_agent_queue.go
Labels: bug, enhancement

#1185 `azuredevops_build_definition ` - Change `name` from optional to required
  azuredevops/internal/service/build/resource_build_definition.go
  website/docs/r/build_definition.html.markdown
Labels: enhancement, breaking-change

#1181 Feature: `azuredevops_git_repository` - Support enabled/disable repository
  azuredevops/internal/acceptancetests/resource_git_repository_test.go
  azuredevops/internal/service/git/resource_git_repository.go
  azuredevops/internal/service/git/resource_git_repository_test.go
  website/docs/r/git_repository.html.markdown
Labels: enhancement

#1195 [Document] `azuredevops_build_definition_permissions` - Update pipeline permission document
  website/docs/r/build_definition_permissions.html.markdown
Labels: documentation, permission

#1200 Data Source - `azuredevops_serviceendpoint_bitbucket`
  azuredevops/internal/acceptancetests/data_serviceendpoint_bitbucket_test.go
  azuredevops/internal/service/serviceendpoint/data_serviceendpoint_bitbucket.go
  azuredevops/provider.go
  website/azuredevops.erb
  website/docs/d/serviceendpoint_bitbucket.html.markdown
Labels: documentation, new-data-source, size/M, service
