Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2024-09, with the labels that each got.

#1157 [Bug Fix] - `azuredevops_agent_queue` - Fix name get/set bug
  azuredevops/internal/acceptancetests/resource_agent_queue_test.go
  azuredevops/internal/service/taskagent/resource_agent_queue.go
Labels: bug, crash

#1159 Adding nil check to project ID of sonarqube service endpoint
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_sonarqube.go
Labels: bug

#1166 `azuredevops_wiki` Add support for delete project wiki
  azuredevops/internal/service/wiki/resource_wiki.go
  website/docs/r/wiki.html.markdown
Labels: enhancement

#1079 New Resource - `azuredevops_wiki_page`
  azuredevops/internal/acceptancetests/resource_wiki_page_test.go
  azuredevops/internal/service/wiki/resource_wiki_page.go
  azuredevops/provider.go
  website/docs/r/wiki_page.html.markdown
Labels: new-resource, new-feature
