Repository microsoft/terraform-provider-azuredevops, pull requests merged in 2025-04, with the labels that each got.

#1341 Docs - Fixed typo (`manage` to `managed`) and updated Azure AD to Entra ID
  website/docs/index.html.markdown
Labels: documentation

#1343 [Enhance] -`azuredevops_git_repository` - git repo ephemeral password
  azuredevops/internal/acceptancetests/resource_git_repository_test.go
  azuredevops/internal/service/git/resource_git_repository.go
  azuredevops/internal/service/git/resource_git_repository_test.go
  azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_generic_git.go
  website/docs/r/git_repository.html.markdown
Labels: enhancement, new-feature

#1356 `azuredevops_git_repository` - Set the timeout to create timeout, customizable via timeouts in hcl
  azuredevops/internal/service/git/resource_git_repository.go
Labels: enhancement

#1358 [Document] `azuredevops_git_permissions`- Update git permission document
  website/docs/r/git_permissions.html.markdown
Labels: documentation, permission

#1359 [New Data Source] `azuredevops_serviceendpoint_dockerregistry`
  azuredevops/internal/acceptancetests/data_serviceendpoint_dockerregistry_test.go
  azuredevops/internal/service/serviceendpoint/data_serviceendpoint_dockerregistry.go
  azuredevops/provider.go
  azuredevops/provider_test.go
  website/docs/d/serviceendpoint_dockerregistry.html.markdown
Labels: new-data-source, service connection

#1360 [Document] - Update data `azuredevops_group` and data `azuredevops_groups` document
  website/docs/d/group.html.markdown
  website/docs/d/groups.html.markdown
Labels: documentation
